import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css'
import '../styles/prosemirror.css'
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn(inter.className, 'bg-green-300')}>
				<ThemeProvider
					defaultTheme='system'
					attribute='class'
					enableSystem
					disableTransitionOnChange
				>
					<main className='max-w-full h-screen'>{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
